from __future__ import annotations

from jinja2 import Template

from agent.summarization.models import PulseSummary

EMAIL_TEMPLATE_HTML = """
<html>
  <head>
    <style>
      body { font-family: Arial, sans-serif; color: #1f2937; line-height: 1.5; }
      .card { border: 1px solid #e5e7eb; border-radius: 10px; padding: 16px; margin-bottom: 14px; }
      .muted { color: #6b7280; font-size: 13px; }
      .chip {
        display: inline-block;
        background: #eef2ff;
        color: #3730a3;
        padding: 2px 8px;
        border-radius: 999px;
        font-size: 12px;
        margin-right: 6px;
      }
      h2, h3 { margin-bottom: 8px; }
      ol, ul { margin-top: 6px; }
    </style>
  </head>
  <body>
    <h2>Weekly Pulse: {{ summary.product }} ({{ summary.window.iso_week }})</h2>
    <p class="muted">Window: {{ summary.window.start }} to {{ summary.window.end }}</p>

    <div class="card">
      <span class="chip">Top 3 Themes</span>
      <ul>
      {% for theme in summary.top_themes[:3] %}
        <li><strong>{{ theme.label }}</strong> — {{ theme.description }}</li>
      {% endfor %}
      </ul>
    </div>

    <div class="card">
      <span class="chip">3 User Quotes</span>
      <ol>
      {% for quote in summary.quotes[:3] %}
        <li>"{{ quote.text }}"</li>
      {% endfor %}
      </ol>
    </div>

    <div class="card">
      <span class="chip">3 Action Ideas</span>
      <ol>
      {% for action in summary.action_ideas[:3] %}
        <li><strong>{{ action.title }}</strong> — {{ action.detail }}</li>
      {% endfor %}
      </ol>
    </div>

    <p><a href="{DOC_DEEP_LINK}"><strong>Read full report</strong></a></p>
    <hr/>
    <p>Generated by Pulse Agent.</p>
  </body>
</html>
""".strip()

EMAIL_TEMPLATE_TEXT = """
Weekly Pulse: {{ summary.product }} ({{ summary.window.iso_week }})

Top 3 themes:
{% for theme in summary.top_themes[:3] -%}
- {{ theme.label }}: {{ theme.description }}
{% endfor %}

3 user quotes:
{% for quote in summary.quotes[:3] -%}
- "{{ quote.text }}"
{% endfor %}

3 action ideas:
{% for action in summary.action_ideas[:3] -%}
- {{ action.title }}: {{ action.detail }}
{% endfor %}

Read full report: {DOC_DEEP_LINK}
Generated by Pulse Agent.
""".strip()


def render_email(summary: PulseSummary) -> tuple[str, str, str]:
    top_theme = summary.top_themes[0].label if summary.top_themes else "Top Themes"
    subject = f"[Weekly Pulse] {summary.product} — {summary.window.iso_week} — {top_theme}"
    html = Template(EMAIL_TEMPLATE_HTML).render(summary=summary)
    text = Template(EMAIL_TEMPLATE_TEXT).render(summary=summary)
    return subject, html, text
