from __future__ import annotations

from jinja2 import Template

from agent.summarization.models import PulseSummary

EMAIL_TEMPLATE_HTML = """
<html>
  <body>
    <h2>Weekly Pulse: {{ summary.product }} ({{ summary.window.iso_week }})</h2>
    <p>Top themes this week:</p>
    <ul>
    {% for theme in summary.top_themes %}
      <li><strong>{{ theme.label }}</strong> — {{ theme.description }}</li>
    {% endfor %}
    </ul>
    <p><a href="{DOC_DEEP_LINK}">Read full report →</a></p>
    <hr/>
    <p>Generated by Pulse Agent.</p>
  </body>
</html>
""".strip()

EMAIL_TEMPLATE_TEXT = """
Weekly Pulse: {{ summary.product }} ({{ summary.window.iso_week }})

Top themes:
{% for theme in summary.top_themes -%}
- {{ theme.label }}: {{ theme.description }}
{% endfor %}

Read full report: {DOC_DEEP_LINK}
Generated by Pulse Agent.
""".strip()


def render_email(summary: PulseSummary) -> tuple[str, str, str]:
    top_theme = summary.top_themes[0].label if summary.top_themes else "Top Themes"
    subject = f"[Weekly Pulse] {summary.product} — {summary.window.iso_week} — {top_theme}"
    html = Template(EMAIL_TEMPLATE_HTML).render(summary=summary)
    text = Template(EMAIL_TEMPLATE_TEXT).render(summary=summary)
    return subject, html, text
